server: 
  port: 8088
  servlet:
    context-path: /automation-test

spring: 
  thymeleaf: 
    cache: false
  messages: 
    basename: messages
  datasource: 
    name: automation-test
    url: jdbc:derby:out/automation_test;create=true  
    type: com.alibaba.druid.pool.DruidDataSource  
    driver-class-name: org.apache.derby.jdbc.EmbeddedDriver  

logging: 
    config: classpath:logback.xml

logback: 
  root: /var/log/automationtest
  appname: ecaprules
  maxhistory: 30
  maxfilesize: 1MB

webdriver:
  gecko:
    driver: classpath:/geckodriver
  chrome:
    driver: C:\\catools\\chromedriver.exe
  selected: gecko
# wait before each action
  wait: 2
# timeout for each action
  timeout: 10


jobs: 
  # job Execute the annotated method with a fixed period in milliseconds between
  # the end of the last invocation and the start of the next.
  fixedDelay: 10000
