server: 
  port: 8088
  servlet:
    context-path: /automation-test

spring: 
  thymeleaf: 
    cache: false
  messages: 
    basename: messages
  datasource: 
    name: wf_orchestrator
    url: jdbc:derby:out/automation_test;create=true  
    type: com.alibaba.druid.pool.DruidDataSource  
    driver-class-name: org.apache.derby.jdbc.EmbeddedDriver  
    initialSize: 5  
    minIdle: 5  
    maxActive: 20  
    maxWait: 60000  
    timeBetweenEvictionRunsMillis: 60000  
    minEvictableIdleTimeMillis: 300000  
    filters: stat  
    validationQuery: select 1 from sysibm.sysdummy1
    testWhileIdle: true  
    testOnBorrow: false  
    testOnReturn: false  
    poolPreparedStatements: true  
    maxOpenPreparedStatements: 20  
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000  

logging: 
    config: classpath:logback.xml

webdriver:
  gecko:
    driver: classpath:/geckodriver
  chrome:
    driver: C:\\catools\\chromedriver.exe
  selected: gecko
# wait before each action
  wait: 2
# timeout for each action
  timeout: 10


jobs:
  # job Execute the annotated method with a fixed period in milliseconds between
  # the end of the last invocation and the start of the next.
  fixedDelay: 10000
